CREATE TABLE token_revocation_list (
    jti VARCHAR2(255 CHAR) CONSTRAINT token_revocation_list_pk PRIMARY KEY,
    rvt TIMESTAMP(3) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
    exp TIMESTAMP(3) WITH TIME ZONE NOT NULL
);
